/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { IUser } from "./../../structures/user/user";

/**
 * this is sample api
 * @summary user find by user id
 * @tag users
 * @param user_id user id
 * @return user info
 * @throw 404 Not Found
 * 
 * @controller UsersController.getOne()
 * @path GET /users/:user_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getOne(
    connection: IConnection,
    user_id: string,
): Promise<getOne.Output> {
    return Fetcher.fetch(
        connection,
        getOne.ENCRYPTED,
        getOne.METHOD,
        getOne.path(user_id),
    );
}
export namespace getOne {
    export type Output = IUser;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/:user_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (user_id: string): string => {
        return `/users/${encodeURIComponent(user_id ?? "null")}`;
    }
}

/**
 * @controller UsersController.create()
 * @path POST /users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
    connection: IConnection,
    body: IUser.ICreate1,
): Promise<void> {
    return Fetcher.fetch(
        connection,
        create.ENCRYPTED,
        create.METHOD,
        create.path(),
        body,
        create.stringify,
    );
}
export namespace create {
    export type Input = IUser.ICreate1;

    export const METHOD = "POST" as const;
    export const PATH: string = "/users";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/users`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}