/**
 * @packageDocumentation
 * @module api.functional.auth.sign_in.kakao
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import type { IAuthentication } from "./../../../../structures/authentication";
/**
 * @controller SignInKakaoController.execute()
 * @path POST /auth/sign-in/kakao
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function execute(connection: IConnection, body: IAuthentication.ISignIn): Promise<void>;
export declare namespace execute {
    type Input = IAuthentication.ISignIn;
    const METHOD: "POST";
    const PATH: string;
    const ENCRYPTED: Fetcher.IEncrypted;
    const path: () => string;
    const simulate: (connection: IConnection, body: execute.Input) => Promise<void>;
    const stringify: (input: Input) => string;
}
