/**
 * @packageDocumentation
 * @module api.functional.auth.oauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

/**
 * 카카오 인증 로그인 페이지 주소 요청
 *
 * @summary 카카오 인증 페이지 주소 요청
 * @tag authentication
 * @return 카카오 인증 페이지 주소
 *
 * @controller AuthController.kakao()
 * @path GET /auth/oauth/kakao
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function kakao(connection: IConnection): Promise<kakao.Output> {
    return !!connection.simulate
        ? kakao.simulate(connection)
        : Fetcher.fetch(
              connection,
              kakao.ENCRYPTED,
              kakao.METHOD,
              kakao.path(),
          );
}
export namespace kakao {
    export type Output = string;

    export const METHOD = "GET" as const;
    export const PATH: string = "/auth/oauth/kakao";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/auth/oauth/kakao`;
    };
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
    ): Promise<Output> => {
        return random(
            typeof connection.simulate === "object" &&
                connection.simulate !== null
                ? connection.simulate
                : undefined,
        );
    };
}

/**
 * 깃허브 인증 로그인 페이지 주소 요청
 *
 * @summary 깃허브 인증 페이지 주소 요청
 * @tag authentication
 * @return 깃허브 인증 페이지 주소
 *
 * @controller AuthController.github()
 * @path GET /auth/oauth/github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function github(connection: IConnection): Promise<github.Output> {
    return !!connection.simulate
        ? github.simulate(connection)
        : Fetcher.fetch(
              connection,
              github.ENCRYPTED,
              github.METHOD,
              github.path(),
          );
}
export namespace github {
    export type Output = string;

    export const METHOD = "GET" as const;
    export const PATH: string = "/auth/oauth/github";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/auth/oauth/github`;
    };
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
    ): Promise<Output> => {
        return random(
            typeof connection.simulate === "object" &&
                connection.simulate !== null
                ? connection.simulate
                : undefined,
        );
    };
}
